/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#if ANDROID
#include <TurboModule.h>
#else
#include <ReactCommon/TurboModule.h>
#endif

namespace facebook {
namespace react {
class JSI_EXPORT SchemaCxxSpecJSI : public TurboModule {
protected:
  SchemaCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
virtual jsi::String nativeTrim(jsi::Runtime &rt, const jsi::String &text) = 0;

};

} // namespace react
} // namespace facebook
