require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'rnfbjni' do
  use_unimodules!
  config = use_native_modules!

  # pod 'gRPC'
  # pod 'gRPC-C++'
  # pod '!ProtoCompiler-gRPCCppPlugin'#, :path => '/Users/karolbisztyga/Desktop/workspace/tmp/grpc/src/objective-c/!ProtoCompiler-gRPCCppPlugin.podspec'
  # pod 'Proto', :path => '.'
  pod 'gRPC-C++'
  pod 'gRPC-C++/Protobuf'
  pod 'Protobuf-C++', '3.15.8'
  # pod 'Protobuf', '3.15.8'

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
