/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#include "NativeModules.h"

namespace facebook {
namespace react {

static jsi::Value __hostFunction_SchemaCxxSpecJSI_nativeTrim(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<SchemaCxxSpecJSI *>(&turboModule)->nativeTrim(rt, args[0].getString(rt));
}

SchemaCxxSpecJSI::SchemaCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("TrimTurboModule", jsInvoker) {
  methodMap_["nativeTrim"] = MethodMetadata {1, __hostFunction_SchemaCxxSpecJSI_nativeTrim};
}


} // namespace react
} // namespace facebook
